### ISSUE TITLE
Problem with css loader?

### ISSUE THREAD

**Issue by mike-barnett** [microsoft/just#110]
I started with an Office Fabric template that uses TypeScript and React and Just. When I tried to add an "import" statement for a .css file into the App.tsx file, I got a compiler error that said I needed a loader. I ended up having to put the following code into my webpack.config.js in order to get it to work. But I'm hoping there is something I did wrong or some simpler setting I can change to get the same effect.

`module.exports.module.rules.push(
    {
        test: /\.css$/,
        use: ['style-loader', 'css-loader'],
    }
);`
`module.exports.resolve.extensions.push('.css');`

**Comment by kenotron** [comment]
The intention is to not force a css style loader by default, but it seems that this is a hindrance to people using this template. I'll add this on by default (css-loader / style-loader)

**Comment by mike-barnett** [comment]
Thanks! That seems like a great plan!

**Comment by mike-barnett** [comment]
Thanks so much! Wonderful!

**Comment by jkovzels** [comment]
I have almost the same situation. Started with Office Fabric React. Tried to add .scss file and got stuck for half of a day. 
Since documentation is almost non-existent and error log for the most part does not provide clear leads I almost give up and was ready to switch to create-app. 

Plus, Office Fabric React uses just-scripts@0.2.0 and there is that bug with `localIdentName` (#236). Upon updating to @latest `npm run start` stopped watching. 

I'm sorry for this rant, but it is super frustrating to use Just now. I would gladly contribute to documentation, but I can not even start figuring out how things are intended to work and what is missing.

**Comment by shytikov** [comment]
Faced this this issue updating `UI Fabric`. Have no idea how to fix without ruining my other changes... Rolling back...

**Comment by shytikov** [comment]
Unfortunately, rolling back become even more painful procedure... So I have tried @mike-barnett approach... And it didn't worked either... 

Preparing for another half of the day wasted...
