### ISSUE TITLE
How to run esm scripts?

### ISSUE THREAD

**Issue by norbertpy** [microsoft/just#176]
I need to import a few things from my `src/` directory for tasks that are written as `esm` modules. Is there any way I can do `babel-node` on the `just-tasks` before calling the `just`?

**Comment by kenotron** [comment]
I am not too familiar with babel-node (or esm or ts-node for that matter). Is it possible to have it registered inside a `just.config.js`?

**Comment by norbertpy** [comment]
Can you point me to where this `just.config.js` is documented? What does it look like?

**Comment by anikethsaha** [comment]
Need some task for `babel` as well I guess. so that the `babel` will run before your task.

There can be a series of task, the babel task will return your esm compile code which then you can use it in `just task`
But it seems not so good solution
@kenotron can we create and export our custom task in `just.config.js` so that we can use this task in another `task` ?  if it so , then its good to have a babel task. other wise we need some other way !

**Comment by kenotron** [comment]
@norbertpy - I decided to let `just-task.js` rest in favor of a file named `just.config.js` so the documentation is the same. It's very much like a `gulpfile.js` where you define all your tasks.

**Comment by kenotron** [comment]
Hope this helps!
