### ISSUE TITLE
option for one task

### ISSUE THREAD

**Issue by arpadcseh** [microsoft/just#188]
Sorry for spamming the issue tracker but I couldn't find the answer for my case. Is it possible to define options for only one task? So for example in just-task.js I would have 2 tasks:
```
option('name', {required: true});
task('say-hello', () => ...);

task('bye', () => ...);
```
and only the say-hello task command would require an argument. Hence when I fire the bye task it wouldn't fail. 
Can I setup just-tasks in this way?

Thanks for the help!

**Comment by kenotron** [comment]
I've had some discussions with folks about this before. The issue here is that that option actually gets passed to all tasks and subtasks. So, we can't really specify a required option for just one task. I think if you really need a required option, you could do it inside the task itself. If you can imagine a good API, feel free to propose that.
