### ISSUE TITLE
Issue with html-webpack-plugin. How to get started after git clone existing project.

### ISSUE THREAD

**Issue by jkovzels** [microsoft/just#290]
Nothing installs `html-webpack-plugin` to `cwd\node_modules` when one does fresh checkout from repo and `yarn install` and when one does `yarn start` whole debugging experience fails. There is no clear indication that something is missing, it just silently fails to use the plugin (see [here](https://github.com/microsoft/just/blob/3f32788be41da61f9df1fc52c50bba58fcf72477/packages/just-scripts/src/webpack/overlays/htmlOverlay.ts#L3))

I have resolved this by `yarn add html-webpack-plugin` but not now it hangs in my `package.json`. I'm not sure that this is optimal. What is the intended way to get started then one clones `just` based project?

I bit of context, a have initialized the project with `npm init uifabric`

**Comment by ecraig12345** [comment]
Sorry nobody responded to this sooner. This behavior is somewhat intentional--not everyone will want to use all the tasks/overlays, so just relies on the user to provide any "optional dependencies" they want to use within their `package.json` (probably as `devDependencies`). But we definitely need a better way to 1) specify what optional dependencies are needed for what tasks/overlays, and 2) warn if they're missing -- see #49.

For the uifabric template specifically, the template definitely ought to include any dependencies needed to run the scaffolded project. So not having `html-webpack-plugin` in that template sounds like a bug.

cc @kenotron

**Comment by ecraig12345** [comment]
Actually it looks like this is fixed in the template now--doing `npm init uifabric` then `yarn start` now works fine. If you're still having issues, please comment.

**Comment by jkovzels** [comment]
@ecraig12345 When I'm back at this, I will check. Thank you for your investigation and reply.
