### ISSUE TITLE
Dependencies?

### ISSUE THREAD

**Issue by be5invis** [microsoft/just#3]
Many task runners and build systems allows dependencies between tasks, and runs a task only when needed. Therefore are there any plan to support dependencies?

A nice dependency system comes from SHAKE, a Haskell build system from Neil Mitchell (@ndmitchell), which allows you to build first then add dependencies like this:

```haskell
"release.tar" %> \_ -> do
    need ["release.txt"]
    files <- lines <$> readFile "release.txt"
    need files
    system "tar" $ ["-cf", "release.tar"] ++ files
```

The Equivalent in TS:
```typescript
task("release.tar", async function(target){
    await target.need("release.txt"); // or maybe "this.need"
    const files = lines(await readFile("release.txt"));
    await need(...files);
    await system("tar", ["-cf", "-release.tar", ...files]);
})
```

**Comment by kenotron** [comment]
To a great extent, just follows the philosophy of gulp 4 (just takes undertaker as a dep that drives the execution order). I found an interesting article about this migration: https://fettblog.eu/gulp-4-parallel-and-series/

It doesn't give the reasoning for why dependencies are gone in gulp 4, but in my experience, these tasks when expressed with task dependencies would unnecessarily tie the different phases together (say,`build:typescript` would then have to know about a task or output of another task). Now, declaring FILE or maybe even artifact inputs and their outputs might be a bit more scalable. 

This is a long comment to agree with you on this feature. Now, I think it is very fascinating API you propose there. What does "target" in the release.tar task mean above?

**Comment by kenotron** [comment]
Also, a note for my future self: http://hackage.haskell.org/package/shake

**Comment by kenotron** [comment]
@be5invis would you want to propose a API here? Or maybe even collaborate?

**Comment by ndmitchell** [comment]
If you're writing a build system I recommend https://github.com/snowleopard/build/releases/download/icfp-final/build-systems.pdf or https://www.youtube.com/watch?v=BQVT6wiwCxM as initial reading. That takes the ideas of Shake, explains them in the context of other build systems, and describes the differences and the subtle choices you are probably making but don't realise.

That said, the design above looks pretty reasonable - good luck!

**Comment by kenotron** [comment]
I think this is a recipe for perpetual complexity in the task orchestration part. At some point, each build system has to make a decision where to draw the line. At v1, I don't think I would want to have a dependency-based system tracking inputs and outputs yet. I am convinced that there's a huge benefit to match the type of direction gulp v4 is heading with a simple DSL to describe task workflow via series / parallel. I'm further convinced that most JS devs don't really care much for the streaming file system concept baked into gulp, and would benefit having a pre-packaged `undertaker` with some arg parsing lib prepackaged. This is the initial goal of `just` and will probably be until we have had more users banging at it requesting for a complex dependency graph of input and output dictating the flow. Might happen one day soon enough. But probably not in the first major release.

This issue is good to keep around for discussion though. I think it's a really good exercise to think through how this kind of system would play out.

**Comment by kenotron** [comment]
I'm closing this as a way to clean house.
