### ISSUE TITLE
just-scripts pulls in a dependency that is being marked as "Malicious component found" by component governance

### ISSUE THREAD

**Issue by vreddi** [microsoft/just#585]
Affected component:
es5-ext
0.10.60

Security Review (CST-E)
This package prints a protest message (in support of Ukraine) upon installation, when the package is installed on a system located in or around Russia. Downgrade to 0.10.53 or an earlier version.

![image](https://user-images.githubusercontent.com/6148930/164778579-b06f5775-adf2-4c54-b5da-5837bbaee1e8.png)

**Comment by ecraig12345** [comment]
Unfortunately I don't think there's a good way to fix this in `just-task` directly until https://github.com/gulpjs/undertaker/pull/97 is merged (removing the `es6-weak-map` dep, since it's not needed in modern Node versions). In the meantime, the most reliable workaround is to add `resolutions` on the consumer's end.

**Comment by ecraig12345** [comment]
`undertaker` finally released a new version, so this is fixed in `just-scripts` 2.3.0 and `just-task` 1.10.0.
