### ISSUE TITLE
security vulnerabilities in marked package

### ISSUE THREAD

**Issue by imjuni** [microsoft/just#592]
Hi, my development environment and github repo. show security vulnerability issue below,

![just-script-audit](https://user-images.githubusercontent.com/1166575/180819894-fb4653eb-194f-4f0d-98df-7e2925547af6.png)

# environment
* win32, macosx
* npm 8.11.0
* node 16.16.0

# issue
marked-terminal latest version is [5.1.1](https://www.npmjs.com/package/marked-terminal). It have a something migration issue?

**Comment by ecraig12345** [comment]
It looks like your version of just-scripts is outdated. Try updating that first.

**Comment by imjuni** [comment]
@ecraig12345 Hi,

I update 2.0.2 > 2.0.4. But raise same problem. 

![화면 캡처 2022-09-15 195203](https://user-images.githubusercontent.com/1166575/190386271-f73df419-84cd-4cfc-9d68-2f84aa3e1aca.png)

**Comment by KtlPro** [comment]
Hello @ecraig12345 is there any chance someone could revisit [this](https://github.com/microsoft/just/pull/662) and bump `marked-terminal` soon? It's creating issues in my team and a large number of dependencies we rely on.

Thanks a bunch.

**Comment by ecraig12345** [comment]
This is fixed now (just published as `just-scripts-utils@1.2.1` and `just-scripts@2.1.1`), but there are a couple of things that I think are important to understand about this situation as it relates to evaluating security alerts in general.

First is that in practice, the impact of "inefficient regular expression complexity" or "regular expression denial of service" vulnerabilities on build systems is pretty low, where the worst thing that could happen is hanging builds (and temporarily reducing productivity while the issue is investigated). They're mainly a concern in the context of web servers, where they could cause denial of service. This is one of the things that makes the npm audit system not particularly useful: it has no way to understand the usage target of a package and downgrade or remove alerts that don't apply, or to allow consuming package owners to mark alerts which don't apply to their usage.

Second is that ironically, after digging into the code, I realized this issue actually had **zero possible impact** on `just-scripts` or `just-task`: the only function using `marked` or `marked-terminal` is `prettyPrintMarkdown`, which is no longer used anywhere (either in just packages, or in fact even [anywhere on GitHub](https://github.com/search?q=prettyPrintMarkdown&type=code) besides outdated `just` forks). So I'm going to make another change removing that function and related deps, and major bumping `just-scripts-utils`.

**Comment by KtlPro** [comment]
Thank you @ecraig12345 !
